name: Arduino Library CI

on: [pull_request, push, repository_dispatch]

jobs:
  spdx:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - name: Checkout Current Repo
      uses: actions/checkout@v2

    - name: check SPDX licensing
      run: python ./SPDX.py

  arduino:
    strategy:
      fail-fast: false
      matrix:
        arduino-platform: ["cpb", "cpc", "cpx_ada", "feather_esp32", "feather_esp8266", "feather32u4", "feather_m0_express", "feather_m4_express", "feather_rp2040", "flora", "funhouse", "gemma", "gemma_m0", "hallowing_m0", "hallowing_m4_tinyusb", "magtag", "metro_m0", "metro_m0_tinyusb", "metro_m4", "metro_m4_tinyusb", "monster_m4sk", "monster_m4sk_tinyusb", "neokeytrinkey_m0", "neotrellis_m4", "nrf52832", "nrf52840", "protrinket_5v", "proxlighttrinkey_m0", "pybadge", "pygamer", "pyportal", "qt2040_trinkey", "qtpy_m0", "qtpy_esp32s2", "rotarytrinkey_m0", "slidetrinkey_m0", "trinket_m0", "uno", "trinket_5v", "ledglasses_nrf52840" ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
         repository: adafruit/ci-arduino
         path: ci

    - name: pre-install
      run: bash ci/actions_install.sh

    # manually install some libraries
    - name: extra libraries
      run: |
        git clone --quiet https://github.com/adafruit/Cryptosuite.git /home/runner/Arduino/libraries/Cryptosuite
        git clone --quiet https://github.com/adafruit/WiFiNINA.git /home/runner/Arduino/libraries/WiFiNINA
        git clone --quiet https://github.com/adafruit/Adafruit_LSM303.git /home/runner/Arduino/libraries/Adafruit_LSM303
        git clone --quiet https://github.com/moderndevice/CapSense.git /home/runner/Arduino/libraries/CapSense
        git clone --quiet https://github.com/PaintYourDragon/ffft.git /home/runner/Arduino/libraries/ffft
        git clone --quiet https://github.com/adafruit/RadioHead.git /home/runner/Arduino/libraries/RadioHead
        git clone --quiet https://github.com/me-no-dev/ESPAsyncTCP /home/runner/Arduino/libraries/ESPAsyncTCP
        git clone --quiet https://github.com/adafruit/Talkie /home/runner/Arduino/libraries/Talkie
        git clone --quiet https://github.com/Infineon/arduino-optiga-trust-m /home/runner/Arduino/libraries/arduinoOptigaTrustM
        git clone --quiet https://github.com/adafruit/HID /home/runner/Arduino/libraries/HID_Project

    - name: test platforms
      run: python3 ci/build_platform.py ${{ matrix.arduino-platform }}


    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}.${{ github.sha }}
        path: |
            build/*.hex
            build/*.bin
            build/*.uf2

    - name: Zip release files
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        if [ -d build ]; then
            (
            echo "Built from Adafruit Learning System Guides `git describe --tags` for ${{ matrix.arduino-platform }}"
            echo "Source code: https://github.com/adafruit/"
            echo "Adafruit Learning System: https://learn.adafruit.com/"
            ) > build/README.txt
            cd build && zip -9 -o ${{ matrix.arduino-platform }}.zip *.hex *.bin *.uf2 *.txt
        fi

    - name: Create release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: build/${{ matrix.arduino-platform }}.zip
        fail_on_unmatched_files: false
        body: "Select the zip file corresponding to your board from the list below."

  pylint:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: "3.x"
    - name: Versions
      run: |
        python3 --version
    - name: Pip install pylint
      run: |
        pip install --force-reinstall pylint==2.7.1
    - name: Checkout Current Repo
      uses: actions/checkout@v2

    - name: lint
      run: ./pylint_check.sh
